name: Deploy Customer

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/customer/**'
      - 'packages/common/**'
      - '.github/workflows/deploy-customer.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build customer package
      run: |
        cd packages/customer
        npm run build
      env:
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_API_VERSION: ${{ secrets.NEXT_PUBLIC_API_VERSION }}
        NEXT_PUBLIC_API_TIMEOUT: ${{ secrets.NEXT_PUBLIC_API_TIMEOUT }}
        NEXT_PUBLIC_MAX_RETRIES: ${{ secrets.NEXT_PUBLIC_MAX_RETRIES }}
        NEXT_PUBLIC_RETRY_DELAY: ${{ secrets.NEXT_PUBLIC_RETRY_DELAY }}
        NEXT_PUBLIC_AUTH_TOKEN_NAME: ${{ secrets.NEXT_PUBLIC_AUTH_TOKEN_NAME }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      run: |
        aws s3 sync packages/customer/dist/ s3://${{ secrets.CUSTOMER_S3_BUCKET }} --delete

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CUSTOMER_CLOUDFRONT_ID }} --paths "/*" 